### ISSUE TITLE
Allow `name` to be an array for Need/Want

### ISSUE THREAD

**Issue by RangerMauve** [allain/react-needs#1]
Something like

```javascript
<Scope>
	<Need name={["foo", "bar"]}>
		{(foo, bar) => `${foo}, ${bar}!`}
	</Need>
	<Offer name="foo" value="Hello" />
	<Offer name="bar" value="World" />
</Scope>

// Will render 

"Hello, World!"
```

**Comment by allain** [comment]
It already supports `<Need value="single-name">...</Need>` and `<Need values={['fod', 'bar']}>...</Need>`.

Same goes for Want.

The determination of what is needed is handled in [parseNeeds](https://github.com/allain/react-needs/blob/master/src/index.js#L56), which handles, arrays, a single string, and a comma separated list of names.

**Comment by RangerMauve** [comment]
Awesome!
